=== nivethsaran/PlacementPortal/review2/XML/XSD/courses.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="courses">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="course" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="courseid"/>
              <xs:element type="xs:string" name="coursename"/>
              <xs:element type="xs:string" name="topicname"/>
              <xs:element type="xs:string" name="department"/>
              <xs:element type="xs:string" name="courseurl"/>
              <xs:element type="xs:string" name="facultyid"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nivethsaran/PlacementPortal/review2/XML/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet href="shoppingcart.xsl" type="text/xsl" ?> -->
<!DOCTYPE courses SYSTEM "DTD/courses.dtd">
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD/courses.xsd">
	<course>
		<courseid>1</courseid>
		<coursename>NCP</coursename>
		<topicname>J2EE</topicname>
		<department>CSE</department>
		<courseurl>https://www.youtube.com/watch?v=vJ-Zn4fo0MQ</courseurl>
		<facultyid>CB.EN.U4CSEFAC01</facultyid>
	</course>
</courses>
